{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "OpenAPI definition",
    "version" : "v0"
  },
  "servers" : [ {
    "url" : "http://localhost:8888",
    "description" : "Generated server url"
  } ],
  "paths" : {
    "/stocks" : {
      "get" : {
        "tags" : [ "stock-controller" ],
        "operationId" : "checkProductAvailability",
        "parameters" : [ {
          "name" : "productCode",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "storeId",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "requiredQuantity",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "boolean"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "stock-controller" ],
        "operationId" : "consumeStock",
        "parameters" : [ {
          "name" : "productCode",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "quantity",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "soreId",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "stock-controller" ],
        "operationId" : "addStock",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/StockDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/stocks/" : {
      "put" : {
        "tags" : [ "stock-controller" ],
        "operationId" : "updateStock",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/StockDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/stores/" : {
      "post" : {
        "tags" : [ "store-controller" ],
        "operationId" : "createStore",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/StoreDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/stores" : {
      "get" : {
        "tags" : [ "store-controller" ],
        "operationId" : "getStores",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/StoreDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/stores/{storeId}" : {
      "get" : {
        "tags" : [ "store-controller" ],
        "operationId" : "getStoreById",
        "parameters" : [ {
          "name" : "storeId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "tags" : [ "store-controller" ],
        "operationId" : "deleteStore",
        "parameters" : [ {
          "name" : "storeId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/historys" : {
      "get" : {
        "tags" : [ "stock-history-controller" ],
        "operationId" : "getHistorys",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/StockHistoryDto"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "StockDto" : {
        "required" : [ "productCode", "productName" ],
        "type" : "object",
        "properties" : {
          "productCode" : {
            "type" : "string"
          },
          "productName" : {
            "type" : "string"
          },
          "quantity" : {
            "minimum" : 1,
            "type" : "integer",
            "format" : "int32"
          },
          "storeId" : {
            "minimum" : 1,
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "StoreDto" : {
        "required" : [ "location", "name" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "location" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          }
        }
      },
      "StockHistoryDto" : {
        "type" : "object",
        "properties" : {
          "productCode" : {
            "type" : "string"
          },
          "productName" : {
            "type" : "string"
          },
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "previousQuantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "currentQuantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "action" : {
            "type" : "string"
          },
          "date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "storeId" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      }
    }
  }
}